/**
 * WuzlHub API
 * A simple api
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Http, Headers, RequestOptionsArgs, Response, URLSearchParams} from '@angular/http';
import {Injectable, Optional} from '@angular/core';
import {Observable} from 'rxjs/Observable';
import 'rxjs/Rx';

/* tslint:disable:no-unused-variable member-ordering */

'use strict';
import {LiveResult} from "../model/live-result";
import {environment} from "../../environments/environment";

@Injectable()
export class LiveResultApi {
    protected basePath = environment.baseApiPath;
    public defaultHeaders : Headers = new Headers();

    constructor(protected http: Http, @Optional() basePath: string) {
        if (basePath) {
            this.basePath = basePath;
        }
    }

    /**
     *
     *
     * @param matchId
     * @param dateTime
     */
    public LiveResultByMatchIdByDateTimeGet (matchId: number, dateTime: Date, extraHttpRequestParams?: any ) : Observable<{}> {
        const path = this.basePath + '/api/LiveResult/{matchId}/{dateTime}'
            .replace('{' + 'matchId' + '}', String(matchId))
            .replace('{' + 'dateTime' + '}', String(dateTime));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'matchId' is not null or undefined
        if (matchId === null || matchId === undefined) {
            throw new Error('Required parameter matchId was null or undefined when calling apiLiveResultByMatchIdByDateTimeGet.');
        }
        // verify required parameter 'dateTime' is not null or undefined
        if (dateTime === null || dateTime === undefined) {
            throw new Error('Required parameter dateTime was null or undefined when calling apiLiveResultByMatchIdByDateTimeGet.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     *
     *
     * @param id
     */
    public LiveResultFindresultsbymatchByIdGet (id: string, extraHttpRequestParams?: any ) : Observable<{}> {
        const path = this.basePath + '/api/LiveResult/findresultsbymatch/{id}'
            .replace('{' + 'id' + '}', String(id));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiLiveResultFindresultsbymatchByIdGet.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     *
     *
     * @param liveResult
     */
    public LiveResultPost (liveResult?: LiveResult, extraHttpRequestParams?: any ) : Observable<{}> {
        const path = this.basePath + '/api/LiveResult';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        let requestOptions: RequestOptionsArgs = {
            method: 'POST',
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(liveResult);

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

}
