/**
 * WuzlHub API
 * A simple api
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Http, Headers, RequestOptionsArgs, Response, URLSearchParams} from '@angular/http';
import {Injectable, Optional} from '@angular/core';
import {Observable} from 'rxjs/Observable';
import 'rxjs/Rx';

/* tslint:disable:no-unused-variable member-ordering */

'use strict';
import {Tournament} from "../model/tournament";
import {environment} from "../../environments/environment";

@Injectable()
export class TournamentApi {
    protected basePath = environment.baseApiPath;
    public defaultHeaders : Headers = new Headers();

    constructor(protected http: Http, @Optional() basePath: string) {
        if (basePath) {
            this.basePath = basePath;
        }
    }

    /**
     *
     *
     * @param id
     */
    public TournamentByIdGet (id: number, extraHttpRequestParams?: any ) : Observable<{}> {
        const path = this.basePath + '/api/Tournament/{id}'
            .replace('{' + 'id' + '}', String(id));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiTournamentByIdGet.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     *
     *
     * @param tournamentId
     * @param amount
     */
    public TournamentByTournamentIdCreatematchesByAmountGet (tournamentId: number, amount: number, extraHttpRequestParams?: any ) : Observable<{}> {
        const path = this.basePath + '/api/Tournament/{tournamentId}/creatematches/{amount}'
            .replace('{' + 'tournamentId' + '}', String(tournamentId))
            .replace('{' + 'amount' + '}', String(amount));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'tournamentId' is not null or undefined
        if (tournamentId === null || tournamentId === undefined) {
            throw new Error('Required parameter tournamentId was null or undefined when calling apiTournamentByTournamentIdCreatematchesByAmountGet.');
        }
        // verify required parameter 'amount' is not null or undefined
        if (amount === null || amount === undefined) {
            throw new Error('Required parameter amount was null or undefined when calling apiTournamentByTournamentIdCreatematchesByAmountGet.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     *
     *
     * @param tournamentId
     */
    public TournamentByTournamentIdGetmatchesGet (tournamentId: number, extraHttpRequestParams?: any ) : Observable<{}> {
        const path = this.basePath + '/api/Tournament/{tournamentId}/getmatches'
            .replace('{' + 'tournamentId' + '}', String(tournamentId));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'tournamentId' is not null or undefined
        if (tournamentId === null || tournamentId === undefined) {
            throw new Error('Required parameter tournamentId was null or undefined when calling apiTournamentByTournamentIdGetmatchesGet.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     *
     *
     * @param tournamentId
     */
    public TournamentByTournamentIdGetplayersGet (tournamentId: number, extraHttpRequestParams?: any ) : Observable<{}> {
        const path = this.basePath + '/api/Tournament/{tournamentId}/getplayers'
            .replace('{' + 'tournamentId' + '}', String(tournamentId));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'tournamentId' is not null or undefined
        if (tournamentId === null || tournamentId === undefined) {
            throw new Error('Required parameter tournamentId was null or undefined when calling apiTournamentByTournamentIdGetplayersGet.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     *
     *
     * @param tournamentId
     * @param playerIds
     */
    public TournamentByTournamentIdInsertplayersPost (tournamentId: number, playerIds?: Array<number>, extraHttpRequestParams?: any ) : Observable<{}> {
        const path = this.basePath + '/api/Tournament/{tournamentId}/insertplayers'
            .replace('{' + 'tournamentId' + '}', String(tournamentId));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'tournamentId' is not null or undefined
        if (tournamentId === null || tournamentId === undefined) {
            throw new Error('Required parameter tournamentId was null or undefined when calling apiTournamentByTournamentIdInsertplayersPost.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'POST',
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(playerIds);

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     *
     *
     */
    public TournamentGet (extraHttpRequestParams?: any ) {
        const path = this.basePath + '/api/Tournament';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     *
     *
     * @param tournament
     */
    public TournamentPost (tournament?: Tournament, extraHttpRequestParams?: any ) : Observable<{}> {
        const path = this.basePath + '/api/Tournament';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        let requestOptions: RequestOptionsArgs = {
            method: 'POST',
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(tournament);

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

}
